{% set name = "agent-client-protocol" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-','_') }}-{{ version }}.tar.gz
    sha256: f8a6041e27423131e42e4d0cdd850d5b094b1092f79cc29501ab2bd57b92ee88

build:
  skip: true  # [py<310]
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - python
    - pdm-backend
    - pip
  run:
    - python
    - pydantic >=2.7
  run_constrained:
    # logfire
    - logfire >=0.14
    - opentelemetry-sdk >=1.28.0

tests:
  - python:
      imports:
        - acp
      pip_check: true
      python_version:

about:
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/agentclientprotocol/python-sdk
  summary: A Python implement of Agent Client Protocol (ACP, by Zed Industries).

extra:
  recipe-maintainers:
    - davidbrochart
