{% set name = "agent-client-protocol" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-','_') }}-{{ version }}.tar.gz
    sha256: f744c48ab9af0f0b4452e5ab5498d61bcab97c26dbe7d6feec5fd36de49be30b

build:
  skip: true  # [py<310]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - python
    - pdm-backend
    - pip
  run:
    - python
    - pydantic >=2.7
  run_constrained:
    # logfire
    - logfire >=0.14
    - opentelemetry-sdk >=1.28.0

test:
  imports:
    - acp
  requires:
    - pip
  commands:
    - pip_check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"

about:
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/agentclientprotocol/python-sdk
  summary: A Python implement of Agent Client Protocol (ACP, by Zed Industries).

extra:
  recipe-maintainers:
    - davidbrochart
